In [7]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

text_data = np.array([
    'I love Newziland newziland',
    'Sweden is good',
    'I hate japan',
    'Germany beats both'
])

count = CountVectorizer()
bag_of_words = count.fit_transform(text_data)
print(bag_of_words)

# 밀집 행렬의 형태로 불러옴
print(bag_of_words.toarray())

  (0, 7)	1
  (0, 8)	2
  (1, 9)	1
  (1, 5)	1
  (1, 3)	1
  (2, 4)	1
  (2, 6)	1
  (3, 2)	1
  (3, 0)	1
  (3, 1)	1
[[0 0 0 0 0 0 0 1 2 0]
 [0 0 0 1 0 1 0 0 0 1]
 [0 0 0 0 1 0 1 0 0 0]
 [1 1 1 0 0 0 0 0 0 0]]


In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

text_data = np.array([
    'I love Newziland',
    'I Newzliand love you',
    'Germany good',
    'Germany beats both',
    'korea is top of the top'
])

tfidf = TfidfVectorizer()
feature_matrix = tfidf.fit_transform(text_data)

print(tfidf.vocabulary_)
print(feature_matrix)
print(feature_matrix.toarray())

{'love': 6, 'newziland': 7, 'newzliand': 8, 'you': 12, 'germany': 2, 'good': 3, 'beats': 0, 'both': 1, 'korea': 5, 'is': 4, 'top': 11, 'of': 9, 'the': 10}
  (0, 7)	0.7782829228046183
  (0, 6)	0.6279137616509933
  (1, 12)	0.6141889663426562
  (1, 8)	0.6141889663426562
  (1, 6)	0.49552379079705033
  (2, 3)	0.7782829228046183
  (2, 2)	0.6279137616509933
  (3, 1)	0.6141889663426562
  (3, 0)	0.6141889663426562
  (3, 2)	0.49552379079705033
  (4, 10)	0.35355339059327373
  (4, 9)	0.35355339059327373
  (4, 11)	0.7071067811865475
  (4, 4)	0.35355339059327373
  (4, 5)	0.35355339059327373
[[0.         0.         0.         0.         0.         0.
  0.62791376 0.77828292 0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.49552379 0.         0.61418897 0.         0.         0.
  0.61418897]
 [0.         0.         0.62791376 0.77828292 0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.61418897 0