In [1]:
import seaborn as sns
import scipy as sp
import scipy.stats

import numpy as np
import pandas as pd

# import pandas_datareader.data as web
#시각화 패키지
import matplotlib.pyplot as plt
import platform
from matplotlib import font_manager, rc

if platform.system() == 'Darwin': rc('font', family='AppleGothic')

import matplotlib 
matplotlib.rcParams['axes.unicode_minus'] = False

from scipy import sparse

ar = np.eye(3, k=1)
print (ar)


[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [2]:
# 스칼라, 벡터, 형렬의 산술 연산
x = np.array([10, 11, 20, 13, 14])

In [3]:
y = np.array({20,30,22, 11, 13})

In [4]:

      # 다른 차원의 벡터를 shafe가 다르면 작은 쪽의 shape를 큰 폭에 맞춰어서 수행함
      # 벡터와 행렬의 연산
      # 벡터의 대이터 개수과 행렬의 열의 개수를 알아야함.)