In [2]:
import seaborn as sns
import scipy as sp
import scipy.stats

import numpy as np
import pandas as pd

# import pandas_datareader.data as web
#시각화 패키지
import matplotlib.pyplot as plt
import platform
from matplotlib import font_manager, rc

if platform.system() == 'Darwin': rc('font', family='AppleGothic')

import matplotlib 
matplotlib.rcParams['axes.unicode_minus'] = False

In [3]:
import random
# 데이터 집단
li = [10,20,30,40,50]

# 복원 추출
# randint (시작위치, 종료위치) -> 면 특정 범위 내의 정수를 리턴
for i in range(5):
    print(li[random.randint(0, len(li)-1)], end=' ')
    
# 비복원 추출
result = random.sample(li, k=5)
print(result)

ar = ["오미크론", "다크스펙터", "나즈", "라투", "위치"]
# 복원 추출
print(np.random.choice(ar,5))
# 8:2 비복원 추출 - 일반적인 머신러닝에서 훈련 데이터와 검증 데이터 분리
sample = np.random.choice(ar,int(len(ar) * 0.8), replace=False)
print(sample)
validation=[]
#데이터를 순회하면서 속하지 않은 데이터만 validation 에 추가
for i in ar :
    if i not in sample :
        validation.append(i)
print(validation)

30 30 30 10 10 [10, 50, 20, 40, 30]
['위치' '오미크론' '위치' '나즈' '위치']
['오미크론' '위치' '라투' '나즈']
['다크스펙터']


In [10]:
ex_df = pd.DataFrame(np.arange(0, 120).reshape(40, 3))

# 10개의 데이터 샘플링
print(ex_df.sample(frac=0.8))

      0    1    2
34  102  103  104
39  117  118  119
14   42   43   44
26   78   79   80
10   30   31   32
2     6    7    8
17   51   52   53
27   81   82   83
19   57   58   59
28   84   85   86
9    27   28   29
21   63   64   65
25   75   76   77
18   54   55   56
32   96   97   98
3     9   10   11
11   33   34   35
31   93   94   95
22   66   67   68
0     0    1    2
35  105  106  107
12   36   37   38
6    18   19   20
16   48   49   50
5    15   16   17
7    21   22   23
36  108  109  110
4    12   13   14
37  111  112  113
24   72   73   74
8    24   25   26
1     3    4    5


In [14]:
# 순차적 분할 - 데이터를 순서대로 분할: shuffle 옵션을 False로 설정

X = np.arange(20).reshape(10, 2)
print(X)

y = np.arange(10)
print(y)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
[0 1 2 3 4 5 6 7 8 9]


In [21]:
# 랜덤 추출
# 이를 가지고 실제 훈련에 사용한다면 시드는 고정시켜야 한다
# 시드를 고정시키지 않으면 선택된 데이터에 따라 다른 모델이 ㅁ나들어지고
# 검증해야 하는 데이터도 랜덤하게 생성되므로 평가지표가 매번 달라지게 된다.
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=False, random_state=42)


In [29]:
X = np.arange(30).reshape(15, 2)
y = np.arange(15)

grep = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=True, stratify=grep,random_state=42)


print (X_train.shape)
print (X_test.shape)
print (X_train)

(10, 2)
(5, 2)
[[ 2  3]
 [14 15]
 [26 27]
 [16 17]
 [ 8  9]
 [28 29]
 [10 11]
 [ 4  5]
 [12 13]
 [20 21]]
