In [1]:
import numpy as np
#3차원 데이터 생성
np.random.seed(4)
m = 60
w1, w2 = 0.1, 0.3
noise = 0.1

angles = np.random.rand(m) * 3 * np.pi / 2 - 0.5
X = np.empty((m, 3))
X[:, 0] = np.cos(angles) + np.sin(angles)/2 + noise * np.random.randn(m) / 2
# 여기서의 0.1 은 잡음을 섞기 위한 것, 아무 숫자나 가능
X[:, 1] = np.sin(angles) * 0.7 + noise * np.random.randn(m) / 2
# 0.1과 0.3은 데이터 변환을 위한 가중치라서 아무거나 가능
X[:, 2] = X[:, 0] * w1 + X[:, 1] * w2 + noise * np.random.randn(m)
# 원본 데이터 5개 출력
print(X)

pca = PCA(n_components=2)



[[-1.01570027 -0.55091331 -0.26132626]
 [-0.00771675  0.59958572  0.03507755]
 [-0.95317135 -0.46453691 -0.24920288]
 [-0.92012304  0.21009593  0.02182381]
 [-0.76309739  0.158261    0.19152496]
 [ 1.11816122  0.32508721  0.31710572]
 [-1.02258878 -0.64384064 -0.13368695]
 [ 0.67351984 -0.27342519 -0.00787835]
 [ 1.01619558  0.51546608  0.46783297]
 [ 0.54957723  0.67728016  0.2340159 ]
 [-0.98960443  0.00886617 -0.12152034]
 [ 1.13248106  0.28229967  0.06972972]
 [-0.99337712 -0.26832824 -0.15761101]
 [-0.94763679 -0.4995849  -0.13927911]
 [ 1.10095709  0.1706481   0.09790432]
 [-0.34604591  0.45334414  0.06433843]
 [ 0.69102621 -0.27337761 -0.05926516]
 [ 0.68302902  0.70421846  0.24642318]
 [ 0.8774031  -0.16775101 -0.02162333]
 [-1.06090127 -0.48213721 -0.38573526]
 [ 0.52336644  0.66585845  0.39019099]
 [-0.94419403 -0.61502157 -0.47610118]
 [-0.9716288   0.00742468 -0.18764369]
 [-1.10560661 -0.31903307 -0.17189644]
 [ 1.1748694   0.15718214  0.26579776]
 [ 0.91337123 -0.1608149 

In [2]:
#SVD를 이용한 주성분 구하기
X_centered = X - X.mean(axis=0)
U, s, Vt = np.linalg.svd(X_centered)
c1 = Vt.T[:, 0]
c2 = Vt.T[:, 1]
print(c1)
print(c2)

[0.93636116 0.29854881 0.18465208]
[-0.34027485  0.90119108  0.2684542 ]


In [3]:
# 2차원으로 투영
W2 = Vt.T[:, :2]
X2D = X_centered.dot(W2)
print(X2D[:5])

[[-1.26203346 -0.42067648]
 [ 0.08001485  0.35272239]
 [-1.17545763 -0.36085729]
 [-0.89305601  0.30862856]
 [-0.73016287  0.25404049]]


In [4]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X2D = pca.fit_transform(X)
print(X2D[:5])

# 훈련을 하고 난 후 PCA 인스턴스의 explained_variance_ratio_ 속성에 설명 가능한 분산의 비율을 저장함

[[ 1.26203346  0.42067648]
 [-0.08001485 -0.35272239]
 [ 1.17545763  0.36085729]
 [ 0.89305601 -0.30862856]
 [ 0.73016287 -0.25404049]]


In [5]:
# 분산의 비율
print('설명 가능한 분산의 비율:', pca.explained_variance_ratio_)

# 첫 번째 주성분이 0.842 만큼의 분산을 설명
# 두 번째 주성분이 0.146 만큼의 분산을 설명
# 데이터 셋 분산의 84.2%가 첫 번째 PC를 따라 놓여있고, 14.6%가 두 번째 PC를 따라 놓여있음.
# 잃어버린 비율은 1.1%

설명 가능한 분산의 비율: [0.84248607 0.14631839]


In [7]:
import numpy as np
#3차원 데이터 생성
np.random.seed(4)
m = 60
w1, w2 = 0.1, 0.3
noise = 0.1

angles = np.random.rand(m) * 3 * np.pi / 2 - 0.5
X = np.empty((m, 3))
X[:, 0] = np.cos(angles) + np.sin(angles)/2 + noise * np.random.randn(m) / 2
# 여기서의 0.1 은 잡음을 섞기 위한 것, 아무 숫자나 가능
X[:, 1] = np.sin(angles) * 0.7 + noise * np.random.randn(m) / 2
# 0.1과 0.3은 데이터 변환을 위한 가중치라서 아무거나 가능
X[:, 2] = X[:, 0] * w1 + X[:, 1] * w2 + noise * np.random.randn(m)
# 원본 데이터 5개 출력
print(X[:5])

pca = PCA(n_components=2)
X2D = pca.fit_transform(X)
# 2차원으로 줄어든 데이터를 이요해서 복원
X3D_inverse = pca.inverse_transform(X2D)
print(X3D_inverse[:5])

# 복원 시 데이터가 완벽히 복원되지 않음.


[[-1.01570027 -0.55091331 -0.26132626]
 [-0.00771675  0.59958572  0.03507755]
 [-0.95317135 -0.46453691 -0.24920288]
 [-0.92012304  0.21009593  0.02182381]
 [-0.76309739  0.158261    0.19152496]]
[[-1.01450604 -0.54656333 -0.27441525]
 [-0.02103231  0.55108376  0.18101894]
 [-0.95379477 -0.4668077  -0.24237013]
 [-0.91717404  0.22083765 -0.01049779]
 [-0.74607229  0.22027492  0.00492637]]


In [11]:
# 2개의 배열이 같은 지 확인
print(np.allclose(X, X3D_inverse))
# False

False


In [12]:
print(pca.components_)

[[-0.93636116 -0.29854881 -0.18465208]
 [ 0.34027485 -0.90119108 -0.2684542 ]]
