In [1]:
import numpy as np
import datetime

In [2]:
li = range(1, 1000000)

s = datetime.datetime.now()
print(s)

for i in li:
    i = i * 10
s = datetime.datetime.now()
print(s)

2023-08-07 17:39:14.204032
2023-08-07 17:39:14.332772


In [3]:
ar = np.arange(1, 1000000)
s = datetime.datetime.now()
print("시작시간", s)

ar = ar * 10
s = datetime.datetime.now()
print("종료시간", s)

시작시간 2023-08-07 17:39:14.355550
종료시간 2023-08-07 17:39:14.358787


In [4]:
ar = np.array([1, 2, 3])
print(type(ar)) # ar의 dataType
print(ar.dtype) # dataType
print(ar.ndim) # 몇 차원인지: 1
print(ar.shape) # 3행 0열

<class 'numpy.ndarray'>
int64
1
(3,)


In [5]:
ar = np.array([[1, 2, 3], [4, 5, 6]])

print(ar.ndim) # 몇 차원인지: 2
print(ar.shape) # 2행 3열


2
(2, 3)


In [6]:
ar = np.arange(1, 100, 2)
print(ar)
ar = np.linspace(1, 100, num=9)
print(ar)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[  1.     13.375  25.75   38.125  50.5    62.875  75.25   87.625 100.   ]


In [7]:
# eye - 대각선 방향으로 1을 채운 행렬
ar = np.eye(3)
print(ar)

# [[1. 0. 0.]
# [0. 1. 0.]
# [0. 0. 1.]]

ar = np.eye(3, k=1) # # identity matrix의 시작은 1열부터 시작
print(ar)

# [[0. 1. 0.]
#  [0. 0. 1.]
#  [0. 0. 0.]]

ar = np.eye(3, k=-1) # # identity matrix의 시작은 -1열부터 시작
print(ar)

# [[0. 0. 0.]
#  [1. 0. 0.]
#  [0. 1. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [8]:
ar = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(ar)

# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

br = np.diag(ar)
print(br)

# [1 5 9]

cr = np.diag(ar, k=-1)
print(cr)

# [4 8]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]
[4 8]


In [9]:
ar = np.array([1, 2, '3'])
print(ar)
# ['1' '2' '3']

ar = np.array([1, 2, '3'], dtype=np.int32)
print(ar)
# [1 2 3]

ar = np.array([1, 2, '3'])
print(ar)
# ['1' '2' '3']

br = ar.astype(np.int32)
print(br)
# [1 2 3]

['1' '2' '3']
[1 2 3]
['1' '2' '3']
[1 2 3]


In [10]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

# 1차원으로 변환: 접근 방법을 변환한 것. 이전과 동일한 데이터
ar = matrix.reshape(-1)
print(ar)
ar[0] = 101
print(matrix)
# 두 배열은 같다는 의미. 2차원 배열은 [행, 열], 1차원 배열은 [인덱스]
# 2차원 배열은 1차원 배열의 나열을 의미. 

# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]
# [1 2 3 4 5 6 7 8 9]
# [[101   2   3]
#  [  4   5   6]
#  [  7   8   9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[101   2   3]
 [  4   5   6]
 [  7   8   9]]


In [11]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

# 복제를 해서 1차원으로 변경 - 원본과 다른 데이터를 생성.
br = matrix.flatten()
print(br)
br[0] = 201
print(matrix)

# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]
# [1 2 3 4 5 6 7 8 9]
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)
print(matrix[0][1]) # 0번째 행, 1번째 열.
print(matrix[:][1]) # 전체 행, 1번째 열.
print(matrix[0:2]) # 0 ~ 2번째 행, 전체 열

x = matrix[0][0]
x = 101
print(x, matrix[0][0])
# 행렬 구조는 행을 먼저 선택하고 열을 선택함. -> 행을 생략할 수 없음.

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[4 5 6]
[[1 2 3]
 [4 5 6]]
101 1


In [13]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

x = matrix[0][0]
x = 101
# [행][열] 이렇게 접근하는 경우 slicing. -> 데이터 원본을 복제해서 사용. (데이터 변경 시 데이터 원본 영향 없음)
# [행, 열] 이렇게 접근하는 경우 indexing.
print(x, matrix[0][0])

# Indexing할 때, list를 사용하는 경우 Fancy indexing -> 데이터 원본을 복제해서 사용. (데이터 변경 시 데이터 원본 영향 없음)
# ------------------------------------------------------------------------------------------
# 0번 행을 indexing
ar = matrix[0] 
# 0번 행을 indexing
br = matrix[0 ,]
print(ar, br, sep='\n', end='\n------------------\n')

ar[0] = 100
print('<indexing>',ar, br, matrix[0], sep='\n', end='\n------------------\n')
# ------------------------------------------------------------------------------------------
cr = matrix[[0]]
dr = matrix[0][:]

cr[0, 0] = 101
print('<slicing>', cr, dr, matrix, sep='\n', end='\n------------------\n')
# ------------------------------------------------------------------------------------------

# 101 1
# [1 2 3]
# [1 2 3]
# ------------------
# <indexing>
# [100   2   3]
# [100   2   3]
# [100   2   3]
# ------------------
# <slicing>
# [[101   2   3]]
# [100   2   3]
# [[100   2   3]
#  [  4   5   6]
#  [  7   8   9]]
# ------------------


101 1
[1 2 3]
[1 2 3]
------------------
<indexing>
[100   2   3]
[100   2   3]
[100   2   3]
------------------
<slicing>
[[101   2   3]]
[100   2   3]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]
------------------


In [17]:
ar = np.array([10, 2, 213, 64, 235, 137])
br = np.array([1, 2, 3, 4, 5, 6])

# ndarray는 조건을 줘서 필터링할 수 있다.

print(br[ar >= 30])

[3 4 5 6]
