In [2]:
import numpy as np

In [3]:
li = list(range(1, 10))
print(li)

#listfmf 
ar = np.array(li)
print(ar)

# 일차원 배열을 생성한 후 행과 열의 개수를 3*3 으로 변경.
matrix = np.array(li).reshape((3, 3)) 
print(matrix)

# ndarray의 copy()는 깊은 복사. (원본 영향 없음.)
clone = matrix.copy()
clone[0] = 100
print(matrix)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
data1 = ar[0]
print(data1)

# 2차원 배열에서 데이터 1개 찾아오기
data2 = matrix[0, 0]
data3 = matrix[0][0]
print(data2)
print(data3)

# 이원 배열에서 행 하나 찾아오기
row = matrix[0] # matrix[0][:]
print(row)

# 열 전체를 찾아올 때는 :, 를 사용함. (:은 전체를 의미)
column = matrix[:, 0]
print(column)

1
1
1
[1 2 3]
[1 4 7]


In [5]:
# 일반 인덱싱한 데이터는 파이썬의 기본 데이터와 동일하게 동작한다
# scala data를 복사하는 경우는 원본의 값을 복사해서 대입하기 때문에 서로 영향이 없음.
a = 10
b = a
b = 20
print(a)


# 파이썬의 vector data는 다른 변수에 대입할 때 참조를 복사해서 대입한다.
ax = [1, 2, 3]
# 얕은 복사를 하기 때문에 참조를 대입받는다. 
bx = ax 
bx[0] = 100
print(ax)

10
[100, 2, 3]


In [6]:
# 파이썬에서의 데이터 복제
# copy 모듈의 copy(shallow copy)와 deepcopy 함수 이용
# 얕은 복사는 한 번 복제를 하지만 재귀적으로 수행하지 않음.
# 깊은 복사는 재귀적으로 수행함.

# shallow data

import copy
li = [1, 2, 3]
c = li.copy()
c[0] = 100
print(li)

m = [[1, 2, 3], [4, 5, 6]]
# copy는 1중 중첩까지만 복사하는 것이기 때문에 2중으로 중첨되어 있는 곳의 원소는 복사되지 않
c = m.copy()
c[0][0] = 100
print(m)

d = copy.deepcopy(m)
d[0][0] = 101
print(m)

[1, 2, 3]
[[100, 2, 3], [4, 5, 6]]
[[100, 2, 3], [4, 5, 6]]


## 슬라이싱

In [7]:
li = [[1, 2, 3],[4, 5, 6]]
c = li[0:3]
print(c)
c[0] = 100
print(li)

ar = np.array(li)
d = ar[0:3] # 배열에서 0 ~ 2번째 데이터 복사 - vector data(참조가 복사)
print(d)
d[0] = 100000
print(ar)
print(c is d)

[[1, 2, 3], [4, 5, 6]]
[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
[[100000 100000 100000]
 [     4      5      6]]
False


## Fancy Indexing

In [8]:
# 인덱싱할 때 list를 이용하는 것
ar = np.array([100, 200, 300, 400, 500])
 # 복제 (원본 영향 없음)
f = ar[[0, 2]] 
print(f)
f[0] = 1004
print(ar)

[100 300]
[100 200 300 400 500]


## boolean indexing
bool 배열을 대입해서 True 요소만 추출하는 것

and, or: bool 데이터를 가지고 연산을 수행.
boolean index는 array의 인덱승에 bool 배열을 대입해서 True데이터만 가져오기

In [9]:
ar = np.array([1, 2, 3, 4, 5, 6, 7])
result = ar[[True, True, False, False, True, False, True]]
print(result)

br = np.array([1, 2, 3, 4, 5, 7, 6])
result = ar[(br >= 70) & (br <= 90)]
print(result)

[1 2 5 7]
[]


## ndarray의 연산
- 일반적 연산은 순차적으로 연산
- vectorized된 연산은 코어 개수만큼 계산 가능. [1, 2, 3, 4, 5] + [1, 2, 3, 4, 5] = 한 번에 계산
- broadcast 연산 -> scala 데이터와 vector 데이터 연산할 때 저차원의 데이터를 고차원에 맞춰서 계산함.

In [10]:
ar = np.array([1, 2, 3, 4, 5])
br = np.array([1, 2, 3, 4, 5])

result = ar + br

result = ar + 4

k = (range(1, 11))
# 1차원 배열을 2행 5열로 변경해서 연산을 수행
cr = np.array(k).reshape((2, 5))
print(ar + cr)

[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]


In [11]:
ar = np.array([1, 2, 3, 4, 5])
br = np.array([10, 20, False, 40, 0])

print(ar > br)
print(np.not_equal(ar, br))
print(np.logical_xor(ar, br))


[False False  True False  True]
[ True  True  True  True  True]
[False False  True False  True]


In [12]:
# 벡터화된 함수 적용
# 매개변수에 100을 더해서 리턴하는 함수

def f(i):
    return i + 100
vector_f = np.vectorize(f)
print(vector_f(ar))
print(np.vectorize(lambda i: i+100)(ar))

[101 102 103 104 105]
[101 102 103 104 105]


In [13]:
matrix = np.array(range(1, 11)).reshape((5, 2))
print(matrix)
print(matrix.reshape((2, 5)))
# 행과 열을 변경.
print(matrix.T)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [14]:
cards = np.array(range(1, 49))
print(cards)

print(np.random.permutation(cards))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[32 48  9 42 36  1 15 44 17 24 35 18 46 16 29 28 40 26  5 13  3 12 38 43
  4 41 10  2  8 11 19 21 34 14 25  7 39 37 22 47 31  6 33 27 45 23 20 30]


In [15]:
matrix = np.array([[10, 20], [30, 40], [50, 60]])
print(matrix)
print(matrix.sum())

# 표준 편차
print(matrix.std())

# 표준 편차 - 자유도 1 적용
print(matrix.std(ddof=1))

# 75%에 해당하는 값.
print(np.percentile(matrix, 75))

# axis = 0: 열단위, 1: 행단위
print(matrix.sum(axis=0)) 
print(matrix.sum(axis=1))

# 행 단위 - matrix와 동일한 차원으로 리턴
print(matrix.sum(axis=1, keepdims=True))

print(matrix.argmax(axis=1))
print(matrix.prod(axis=0))

[[10 20]
 [30 40]
 [50 60]]
210
17.07825127659933
18.708286933869708
47.5
[ 90 120]
[ 30  70 110]
[[ 30]
 [ 70]
 [110]]
[1 1 1]
[15000 48000]


In [17]:
ar = np.array([20, 30, 10, 25, 17])
result = np.sort(ar)
print(result)

[ 10  17  20  25  30 100]


In [23]:
x = range(0, 50)
matrix = np.array(x).reshape((10, 5))
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [29]:
cnt = matrix.shape[0]
print(cnt)

k = np.split(matrix, [int(cnt * 0.7)])
print(k)

10
[array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]]), array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])]
